Repository WaspStation-Bot/WaspStation-1.0, pull requests merged in 2021-01, with the labels that each got.

#4 Coom chems
  code/__DEFINES/~wasp_defines/traits.dm
  code/_globalvars/traits.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/mining/ores_coins.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  tgstation.dme
  waspstation/code/datums/diseases/legionvirus.dm
  waspstation/code/datums/mood_events/drug_events.dm
  waspstation/code/datums/mood_events/generic_negative_events.dm
  waspstation/code/game/objects/items/stacks/medical.dm
  waspstation/code/modules/reagents/chemistry/reagents/food_reagents.dm
  waspstation/code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  waspstation/code/modules/reagents/chemistry/reagents/other_reagents.dm
  waspstation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  waspstation/code/modules/reagents/chemistry/recipes/medicine.dm
  waspstation/code/modules/reagents/chemistry/recipes/others.dm
Labels: Stale

#11 add missing sprites
  waspstation/icons/turf/floors/whitesands/ws_floors.dmi
Labels: Sprites, Stale

#7 The Pro Gamer Lavaland Rebalance
  code/datums/components/armor_plate.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/cloaks.dm
  code/modules/mining/equipment/explorer_gear.dm
  code/modules/mining/equipment/kinetic_crusher.dm
  code/modules/mining/equipment/mining_tools.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Stale

#12 bunch of fixes for ws atmos to make it actually functional
  code/__DEFINES/~wasp_defines/atmospherics.dm
  code/controllers/subsystem/weather.dm
  config/atmos_mix.txt
  config/game_options.txt
  waspstation/code/controllers/configuration/entries/game_options.dm
  waspstation/code/controllers/configuration/entries/general.dm
  waspstation/code/game/turf/_whitesands.dm
  waspstation/code/game/turf/open/floor/whitesands.dm
Labels: Config

#9 Command/sec resprite
  code/controllers/subsystem/traumas.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/under/plasmaman.dmi
  icons/mob/clothing/under/security.dmi
  icons/obj/clothing/under/security.dmi
  tgstation.dme
  waspstation/code/game/objects/structures/crates_lockers/closets/secure/security.dm
  waspstation/code/modules/client/loadout/loadout_hat.dm
  waspstation/code/modules/clothing/head/berets.dm
  waspstation/code/modules/clothing/suits/armor.dm
  waspstation/code/modules/clothing/suits/jobs.dm
  waspstation/code/modules/clothing/suits/labcoat.dm
  waspstation/code/modules/clothing/under/jobs/command.dm
  waspstation/code/modules/clothing/under/jobs/security.dm
  waspstation/code/modules/jobs/job_types/brigphys.dm
  waspstation/icons/mob/clothing/hands.dmi
  waspstation/icons/mob/clothing/head.dmi
  waspstation/icons/mob/clothing/suits.dmi
  waspstation/icons/mob/clothing/under/centcom.dmi
  waspstation/icons/mob/clothing/under/command.dmi
  waspstation/icons/mob/clothing/under/security.dmi
  waspstation/icons/obj/clothing/gloves.dmi
  waspstation/icons/obj/clothing/hats.dmi
  waspstation/icons/obj/clothing/suits.dmi
  waspstation/icons/obj/clothing/under/command.dmi
  waspstation/icons/obj/clothing/under/security.dmi
Labels: Sprites, Stale

#8 Deepcore
  _maps/_basemap.dm
  code/datums/mapgen/CaveGenerator.dm
  code/datums/mapgen/Cavegens/LavalandGenerator.dm
  code/modules/mining/machine_vending.dm
  tgstation.dme
  waspstation/code/__DEFINES/DCM.dm
  waspstation/code/datums/dcmnet.dm
  waspstation/code/game/area/dcm/ore_vein.dm
  waspstation/code/game/objects/items/circuitboards/deepcore.dm
  waspstation/code/game/objects/items/pinpointer.dm
  waspstation/code/modules/cargo/packs.dm
  waspstation/code/modules/mining/deepcore/_deepcore.dm
  waspstation/code/modules/mining/deepcore/drill.dm
  waspstation/code/modules/mining/deepcore/equipment.dm
  waspstation/code/modules/mining/deepcore/hopper.dm
  waspstation/code/modules/mining/deepcore/hub.dm
  waspstation/code/modules/research/designs/machine_designs.dm
  waspstation/code/modules/research/techweb/all_nodes.dm
  waspstation/icons/obj/machines/deepcore.dmi
  waspstation/icons/obj/machines/drill.dmi
  waspstation/icons/obj/mining.dmi
Labels: Admin, Config, Github, Map Change, Sprites, Stale

#14 Plant
  code/datums/mapgen/Cavegens/WhitesandsCaves.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/mining/lavaland/ash_flora.dm
  waspstation/code/modules/mining/lavaland/ash_flora.dm
  waspstation/icons/obj/lavaland/newlavalandplants.dmi
Labels: Sprites

#19 Deepcore corrections
  code/datums/mapgen/Cavegens/IcemoonCaves.dm
  code/datums/mapgen/Cavegens/WhitesandsCaves.dm
  code/datums/materials/_material.dm
  code/datums/materials/basemats.dm
  tgstation.dme
  waspstation/code/datums/dcmnet.dm
  waspstation/code/game/area/dcm/ore_vein.dm
  waspstation/code/game/objects/items/circuitboards/deepcore.dm
  waspstation/code/modules/cargo/packs.dm
  waspstation/code/modules/mining/deepcore/_deepcore.dm
  waspstation/code/modules/mining/deepcore/drill.dm
  waspstation/code/modules/mining/deepcore/hopper.dm
  waspstation/code/modules/mining/deepcore/hub.dm
  waspstation/code/modules/mining/deepcore/ore_vein.dm
Labels: Map Change
